title:            Ardour 4
description:      An updated version of the original FLOSS manual.
disqus_shortname: 
reading_time:     true
words_per_minute: 120
url:              https://brunoruviaro.github.io/ardour4-tutorial

#http://localhost:4000 

#http://brunoruviaro.github.io/ardour3-floss-tutorial

# Owner/author information
owner:
  name:           Ardour 4 Tutorial
  avatar:         ardour-icon.png
  bio:            "An updated version of the original Ardour FLOSS Manual."
  email:          
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         brunoruviaro/ardour4-tutorial/
  stackexchange:  
  linkedin:       
  instagram:        
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-66949361-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["drafts", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
